### ISSUE TITLE
Unable to run in local

### ISSUE THREAD

**Issue by Geen-19** [webdevcody/survive-the-night-sim#133] opened 2024-10-26 14:36 UTC
When I try to run this file in my local, I am getting this error'

![image](https://github.com/user-attachments/assets/97bfb3c0-52a1-4a31-a313-3e0fb47d29ce)

**Comment by FleetAdmiralJakob** [comment] 2024-10-27 06:30
What commands did you run? From the start to then end

**Comment by FleetAdmiralJakob** [comment] 2024-10-27 11:01
Btw. there is no convex.config.ts in the /convex dir. Did you run through all the setup steps in the README.md?
<img width="212" alt="image" src="https://github.com/user-attachments/assets/b4a9dc74-8921-4a44-a0ec-b2c125df2f7e">

**Comment by Geen-19** [comment] 2024-10-27 11:11
Yep, went through all the commands, will try on ce again and report to you

**Comment by FleetAdmiralJakob** [comment] 2024-10-27 11:30
Good idea. Thank you

**Comment by FleetAdmiralJakob** [comment] 2024-11-01 19:32
@Geen-19 Any updates on this?

**Comment by delasy** [comment] 2024-11-02 10:37
I was unable to reproduce the problem, I will close this issue now. @Geen-19 feel free to re-open if you are still experiencing same problem.

**Closed by delasy** 2024-11-02 10:37 UTC
Labels: hacktoberfest
